### ISSUE TITLE
Cannot connect wifi on Samsung device (Android 8.0) 

### ISSUE THREAD

**Issue by wklow12** [jflavio1/WifiConnector#7]
Hi, there is an issue when I try to connect wifi on Samsung with android 8.0. I can't connect and there is no any log message that I can use to debug. Is this library compatible with android 8.0 or is Samsung device problem ?

**Comment by wklow12** [comment]
`java.lang.IllegalArgumentException: Illegal char: M at offset 0
                                                            at libcore.util.HexEncoding.toDigit(HexEncoding.java:96)
                                                            at libcore.util.HexEncoding.decode(HexEncoding.java:77)
                                                            at com.android.server.wifi.util.NativeUtil.hexStringToByteArray(NativeUtil.java:318)
                                                            at com.android.server.wifi.util.NativeUtil.hexOrQuotedAsciiStringToBytes(NativeUtil.java:227)
                                                            at com.android.server.wifi.util.NativeUtil.decodeSsid(NativeUtil.java:268)
                                                            at com.android.server.wifi.SupplicantStaNetworkHal.saveWifiConfiguration(SupplicantStaNetworkHal.java:412)
                                                            at com.android.server.wifi.SupplicantStaIfaceHal.addNetworkAndSaveConfig(SupplicantStaIfaceHal.java:405)
                                                            at com.android.server.wifi.SupplicantStaIfaceHal.connectToNetwork(SupplicantStaIfaceHal.java:440)
                                                            at com.android.server.wifi.WifiNative.connectToNetwork(WifiNative.java:851)
                                                            at com.android.server.wifi.WifiStateMachine$ConnectModeState.processMessage(WifiStateMachine.java:8424)
                                                            at com.android.internal.util.StateMachine$SmHandler.processMsg(StateMachine.java:992)
                                                            at com.android.internal.util.StateMachine$SmHandler.handleMessage(StateMachine.java:809)
                                                            at android.os.Handler.dispatchMessage(Handler.java:105)
                                                            at android.os.Looper.loop(Looper.java:164)
                                                            at android.os.HandlerThread.run(HandlerThread.java:65)`

the error get from log

**Comment by jflavio11** [comment]
Hi @wklow12 I have not test the library with many devices on Android Oreo. Have you turned on the logs using the _setLog(true)_ method?

**Comment by kkroid** [comment]
same error here

**Comment by techievex** [comment]
Hey,

I am facing the same error here. We are not able to scan/connect the application in android versions above marshmallow(6.0).

Later I was able to scan the wifi network after by passing permission option and but I am not able to get network ID for the selected network.

Hope you guys can help us out here.

Thanks in advance.
